trigger: none
pr: none

resources:
  pipelines:
    - pipeline: pipeline
      source: 'pipeline1'  # Reference to the Producer Pipeline
      trigger: true        # Automatically trigger this pipeline when the first one completes

parameters:
  - name: dynamicVarFromPipeline1
    type: string
    default: ''

jobs:
- job: UseVariables
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      echo "Received variable: ${{ parameters.dynamicVarFromPipeline1 }}"
    displayName: 'Display the variable from the first pipeline'
